site_name: PHP-MQ
site_url: https://phpmq.michaelrk02.my.id/
repo_url: https://github.com/michaelrk02/php-mq/
site_dir: build/docs
nav:
    - Home: index.md
    - Architecture: architecture.md
    - Implementation: implementation.md
    - API Reference: https://phpmq.michaelrk02.my.id/api
